[package]
name = "fluid"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
three-d = "0.14.1"
rand = "*"
prgrs = "0.6.4"
rayon = "*"
lazy_static = "1.4.0"